CREATE TABLE IF NOT EXISTS NOMNOM(
    NAME TEXT,
    NEIGHBOURHOOD TEXT,
    CUISINE TEXT,
    REVIEW REAL,
    PRICE TEXT,
    HEALTH TEXT
);
INSERT INTO NOMNOM(NAME, NEIGHBOURHOOD, CUISINE, REVIEW, PRICE, HEALTH) VALUES
    ('PETER PARKER', 'BROOKLYN', 'ITALIAN', 4.5, '$10', 'A'),
    ('GANESH', 'TINY TOWN', 'INDIAN', 5, '$3', 'B'),
    ('KUKA', 'APARTMENT', 'AMERICAN', 3, '$11', 'B'),
    ('APPLE', 'APPLE PARK', 'CHINESE', 2, '$20', 'Z');
SELECT * FROM NOMNOM;
SELECT DISTINCT NEIGHBOURHOOD FROM NOMNOM;
SELECT DISTINCT CUISINE FROM NOMNOM;
SELECT * FROM NOMNOM WHERE CUISINE='INDIAN';
SELECT * FROM NOMNOM WHERE REVIEW>=4;
SELECT * FROM NOMNOM WHERE CUISINE='ITALIAN' AND PRICE='$10';
SELECT * FROM NOMNOM WHERE NEIGHBOURHOOD IN('BROOKLYN', 'TINY TOWN', 'APARTMENT');
SELECT * FROM NOMNOM ORDER BY REVIEW DESC LIMIT 5;